#!/usr/bin/bash

# Get terminal dimensions
# WIDTH=$(tput cols)
# HEIGHT=$(tput lines)
WIDTH=$(tput cols < /dev/tty)
HEIGHT=$(tput lines < /dev/tty)

# Calculate horizontal midpoint and prompt position
START_COL=$((WIDTH / 2))
PROMPT_ROW=$((HEIGHT - 4))

START_ROW=1
REMROW=$START_ROW

while getopts "hxc:r:p" arg
do
    case $arg in
        h) usage
           ;;
        x) clear
           ;;
        c) START_COL=$OPTARG
           ;;
        r) START_ROW=$OPTARG
           REMROW=$START_ROW
           ;;
       p)  START_ROW=$(cat .posi)
           REMROW=$START_ROW
           ;;
    esac
done
shift $(($OPTIND - 1))


# Move cursor to the specific Start Row, Column 1 to begin printing
printf "\033[${START_ROW};1H"

# Read file and print
INPUT_SOURCE="/dev/stdin"
cat "$INPUT_SOURCE" | while IFS= read -r line || [ -n "$line" ]; do
    # \033[nG -> Move to midpoint
    # \033[K  -> Clear to end of line
    # %s      -> Print line content
    # \n      -> Move down
    printf "\033[${START_COL}G\033[K%s\n"  "$line"
    REMROW=$((REMROW + 1))
    echo $REMROW > .posi
done

# Move cursor to the second-to-last line for the prompt
printf "\033[${PROMPT_ROW};1H"
