#!/usr/bin/bash
Tmp=/tmp/$$
Tmp0=/tmp/$$_$$
Tmp1=/tmp/$$_$$_$$
Tmp2=/tmp/$$_$$_$$_$$
Tmp3=/tmp/$$_$$_$$_$$_$$
trap 'exit 0' INT HUP QUIT TERM ALRM USR1
trap 'rm -f "$Tmp" "$Tmp0" "$Tmp1" "$Tmp2" "$Tmp3"' EXIT
rm -f "$Tmp" "$Tmp0" "$Tmp1" "$Tmp2" "$Tmp3"  >/dev/null 2>&1;
#  >/dev/null 2>&1;

MESSAGE=""
while getopts "ps:m:b:" arg
do
    case $arg in
        p) cp ~/.vimrc .
           cp ~/.macros.vim .
           cp ~/utils.vim .
           cp ~/commander.vim .
           cp ~/gemini.vim .
           git add -u
           git commit -m "Update"
           git push origin master
           exit 0
           ;;
        s) MESSAGE="$OPTARG"
           MESSAGE="${MESSAGE}__$(date +%Y%m%d_%H%M%S)"
           MESSAGE=`echo $MESSAGE | sed 's/[.,]//g'`
           cp ~/.vimrc .
           cp ~/.macros.vim .
           cp ~/utils.vim .
           cp ~/commander.vim .
           cp ~/gemini.vim .
           git add -u 
           git commit -m "$MESSAGE"
           exit 0
           ;;
        m) MESSAGE="$OPTARG"
           ;;
        b) MESSAGE="$OPTARG"
           ITEM=`echo $MESSAGE | sed 's/[[:space:]]/__/g'`
           MESSAGE="${MESSAGE}__$(date +%Y%m%d_%H%M%S)"
           ITEM=`echo $ITEM | sed 's/[.,]//g'`
           MESSAGE=`echo $MESSAGE | sed 's/[.,]//g'`
           git branch $ITEM
           git checkout $ITEM
           exit 0
           ;;
    esac
done
shift $(($OPTIND - 1))


ITEM="item__$(date +%Y%m%d_%H%M%S)"
if [[ "$MESSAGE" != "" ]]; then                                                                                               
    ITEM=`echo $MESSAGE | sed 's/[[:space:]]/__/g'`
    MESSAGE="${MESSAGE}__$(date +%Y%m%d_%H%M%S)"
    ITEM=`echo $ITEM | sed 's/[.,]//g'`
    MESSAGE=`echo $MESSAGE | sed 's/[.,]//g'`
fi

echo "$MESSAGE"
echo "$ITEM"




git branch $ITEM
git checkout $ITEM
# longhand git checkout -b $ITEM

cp ~/.vimrc .
cp ~/.macros.vim .
cp ~/utils.vim .
cp ~/commander.vim .
cp ~/gemini.vim .

git add -u 

git commit -m "$MESSAGE"

git push origin $ITEM


git checkout master
git merge $ITEM


git push origin master


