#!/usr/bin/bash
Tmp=/tmp/$$


ls -a | gawk '
BEGINE {
    m=-1
}
{
    n = length($0)
    if (n > m) m=n
}
END {
    print m
}' > $Tmp
MAX=`cat $Tmp`

ls -a | gawk -v max="$MAX" '
BEGIN {
    dq="\""
    print "function moveit() {"
    print "    mv --   " dq "$2" dq "    "  dq "$1" dq
    print "}"
    print ""
    print ""
    print ""
    print ""


}


{
    fmt="moveit      %-" max "s" "        %s\n"
    printf fmt, dq $0 dq,dq $0 dq
}' | tee gogo
chmod +x gogo

